/**
 * @forgeui/tokens
 *
 * Design token exports for ForgeUI. Provides:
 * - `tokens` — raw scale values as JS constants (for canvas/WebGL/runtime use)
 * - `semantic` — CSS variable references for palette-aware semantic tokens
 * - `generateCssVars` — produces a CSS variable block string (for SSR or custom injection)
 *
 * Also re-exports all color utilities from `@forgeui/tokens/color`.
 */

// Re-export color utilities so consumers can do:
//   import { darken, alpha } from '@forgeui/tokens'
export * from './color.js'

// Scale imports — generated by scripts/generate-scales.ts
// Hue scales (auto-generated from OKLCH interpolation)
export { blueScale } from './scales/blue.js'
export { redScale } from './scales/red.js'
export { greenScale } from './scales/green.js'
export { amberScale } from './scales/amber.js'
export { purpleScale } from './scales/purple.js'
export { tealScale } from './scales/teal.js'
export { orangeScale } from './scales/orange.js'

// Gray scales (one per palette — manually specified warm/cool tints)
export {
  grayHearthBronzeScale,
  grayMidnightForgeScale,
  grayDeepSpaceScale,
  grayMidnightForgeV2Scale,
} from './scales/gray.js'

// Static scales
export { spacing } from './scales/spacing.js'
export { typography } from './scales/typography.js'
export { radius } from './scales/radius.js'
export { shadows } from './scales/shadows.js'
export { animation } from './scales/animation.js'
export {
  zIndex,
  focusRing,
  opacity,
  iconSize,
  containerWidth,
  backdropBlur,
} from './scales/misc.js'

// ---------------------------------------------------------------------------
// Composite `tokens` object — all raw scale values in one place
// ---------------------------------------------------------------------------

import { blueScale } from './scales/blue.js'
import { redScale } from './scales/red.js'
import { greenScale } from './scales/green.js'
import { amberScale } from './scales/amber.js'
import { purpleScale } from './scales/purple.js'
import { tealScale } from './scales/teal.js'
import { orangeScale } from './scales/orange.js'
import {
  grayHearthBronzeScale,
  grayMidnightForgeScale,
  grayDeepSpaceScale,
  grayMidnightForgeV2Scale,
} from './scales/gray.js'
import { spacing } from './scales/spacing.js'
import { typography } from './scales/typography.js'
import { radius } from './scales/radius.js'
import { shadows } from './scales/shadows.js'
import { animation } from './scales/animation.js'
import {
  zIndex,
  focusRing,
  opacity,
  iconSize,
  containerWidth,
  backdropBlur,
} from './scales/misc.js'

export const tokens = {
  colors: {
    gray: {
      'hearth-bronze': grayHearthBronzeScale,
      'midnight-forge': grayMidnightForgeScale,
      'deep-space': grayDeepSpaceScale,
      'midnight-forge-v2': grayMidnightForgeV2Scale,
    },
    blue: blueScale,
    red: redScale,
    green: greenScale,
    amber: amberScale,
    purple: purpleScale,
    teal: tealScale,
    orange: orangeScale,
  },
  spacing,
  typography,
  radius,
  shadows,
  animation,
  zIndex,
  focusRing,
  opacity,
  iconSize,
  containerWidth,
  backdropBlur,
} as const

// ---------------------------------------------------------------------------
// `semantic` — CSS variable references for active palette tokens
// ---------------------------------------------------------------------------

/**
 * CSS variable references for semantic tokens. These resolve at runtime
 * based on the active palette/mode set by ThemeProvider.
 *
 * For canvas/WebGL use where you need actual hex values, use `useTokens()`
 * from `@forgeui/hooks` instead — it returns resolved values for the active palette.
 */
export const semantic = {
  // Surfaces
  bg: 'var(--forge-bg)',
  surface: 'var(--forge-surface)',
  surfaceRaised: 'var(--forge-surface-raised)',
  surfaceHover: 'var(--forge-surface-hover)',
  surfaceActive: 'var(--forge-surface-active)',
  surfaceSunken: 'var(--forge-surface-sunken)',
  surfaceOverlay: 'var(--forge-surface-overlay)',
  surfacePopover: 'var(--forge-surface-popover)',
  bgOverlay: 'var(--forge-bg-overlay)',
  bgDisabled: 'var(--forge-bg-disabled)',

  // Borders
  border: 'var(--forge-border)',
  borderSubtle: 'var(--forge-border-subtle)',
  borderStrong: 'var(--forge-border-strong)',

  // Accent
  accent: 'var(--forge-accent)',

  // Text
  text: 'var(--forge-text)',
  textMuted: 'var(--forge-text-muted)',
  textDisabled: 'var(--forge-text-disabled)',

  // Text on color
  textOnAccent: 'var(--forge-text-on-accent)',
  textOnInfo: 'var(--forge-text-on-info)',
  textOnSuccess: 'var(--forge-text-on-success)',
  textOnWarning: 'var(--forge-text-on-warning)',
  textOnDanger: 'var(--forge-text-on-danger)',

  // Status
  info: 'var(--forge-info)',
  infoHover: 'var(--forge-info-hover)',
  infoBg: 'var(--forge-info-bg)',
  infoBorder: 'var(--forge-info-border)',
  infoForeground: 'var(--forge-info-foreground)',

  success: 'var(--forge-success)',
  successHover: 'var(--forge-success-hover)',
  successBg: 'var(--forge-success-bg)',
  successBorder: 'var(--forge-success-border)',
  successForeground: 'var(--forge-success-foreground)',

  warning: 'var(--forge-warning)',
  warningHover: 'var(--forge-warning-hover)',
  warningBg: 'var(--forge-warning-bg)',
  warningBorder: 'var(--forge-warning-border)',
  warningForeground: 'var(--forge-warning-foreground)',

  danger: 'var(--forge-danger)',
  dangerHover: 'var(--forge-danger-hover)',
  dangerBg: 'var(--forge-danger-bg)',
  dangerBorder: 'var(--forge-danger-border)',
  dangerForeground: 'var(--forge-danger-foreground)',

  // Selection / highlight
  selectionBg: 'var(--forge-selection-bg)',
  selectionText: 'var(--forge-selection-text)',
  highlightBg: 'var(--forge-highlight-bg)',

  // Scrollbar
  scrollbarTrack: 'var(--forge-scrollbar-track)',
  scrollbarThumb: 'var(--forge-scrollbar-thumb)',
  scrollbarThumbHover: 'var(--forge-scrollbar-thumb-hover)',
} as const

// ---------------------------------------------------------------------------
// `generateCssVars` — for SSR or custom injection
// ---------------------------------------------------------------------------

export type Palette = 'hearth-bronze' | 'midnight-forge' | 'deep-space' | 'midnight-forge-v2'
export type Mode = 'dark' | 'light'

/**
 * Returns the CSS selector string for the given palette and mode combination.
 * Useful for generating inline style blocks during SSR to avoid FOUC.
 *
 * Note: the full variable definitions are in `tokens.css`. This function only
 * returns the selector — import `tokens.css` for the actual variable values.
 */
export function getCssSelector(palette: Palette, mode: Mode): string {
  return `[data-palette="${palette}"][data-theme="${mode}"]`
}
